Azure/azure-sdk-korean

docs/python/documentation.md
I translated the documentation section for python-sdk 
If there is any error, please let me know! 
@ianychoi  @yeongseon
=> Translate python/documentation.md

docs/java/spring.md
Issue: #11 
Translate Namespace and Maven paragraph in Spring.md into Korean.
=> Translate Namespace and Maven paragraph in Spring.md into Korean. #11 

_includes/tables/environment_variables.md, docs/python/documentation.md
=> Docs: python documentation.md

docs/java/spring.md
Issue: #11 
Translate rest part of Spring.md into Korean.
Close #11
=> Translate rest part of Spring.md into Korean.

_data/sidebars/general_sidebar.yml, _data/tables/standard_verbs.yaml, _includes/tables/data_namespaces.md, _includes/tables/mgmt_namespaces.md, docs/general/design.md, docs/tables/registered_namespaces.md
- Issue: Closes #37 
- Translated 'General: API Design' document into Korean.
- Corresponding to: https://azure.github.io/azure-sdk/general_design.html
=> Translate 'General: API Design' into Korean

_data/sidebars/general_sidebar.yml
"iOS Guidelines" 카테고리 명을 "iOS 가이드라인"으로 수정 완료
=> Category name translation: "iOS Guidelines"

_data/sidebars/general_sidebar.yml
.NET Guidelines -> .NET 가이드라인
Closes: #44
=> Category name translation: ".NET Guidelines" 

_data/sidebars/general_sidebar.yml
=> Category name translation: "Python Guidelines"

_includes/info/header.md
=> Fix typo: 사이드 -> 사이트

_data/sidebars/general_sidebar.yml
=> Category name translation: "Policies"

_data/sidebars/general_sidebar.yml
=> Android guidelines>Android 가이드라인

_data/sidebars/general_sidebar.yml
=> Category name translation: ".NET & Python Guidelines" 

_data/sidebars/general_sidebar.yml, docs/android/implementation.md, docs/android/refs.md
translate implementation.md
issue: #74
=> Translate Android:Implementation to Korean

docs/policies/adoption.md
Github저장소 - guideline contribution 파트 한글 번역했습니다.
=> GDLcontrib_ko

docs/python/design.md
Design principles 에서 Diagnosable 부분을 번역해봤습니다.
잘못된 부분이나 가이드가 있다면, 피드백 부탁드리겠습니다. 감사합니다.
I translated the 'Diagnosable' part from 'Design principles'.
This is my first PR. If there are any mistakes or guides, please give feedback. thank you.
=> Translate "Design principles Diagnosable" into Korean in Python design

_data/sidebars/general_sidebar.yml, docs/contribution/cspell.md, docs/contribution/drop.md
#106 관련하여, 새로운 페이지를 간단히 추가했습니다
=> Create page for contribution

_data/sidebars/general_sidebar.yml
번역이 완료된 정책 문서들에 대해서 사이드바 제목을 변경하였습니다.
Closes: #144
=> Fixed sidebar title of policies which is completely translated

_data/sidebars/general_sidebar.yml, docs/policies/reviewprocess.md
세부 내용은 다음과 같습니다.
1. policies의 reviewprocess.md에 대한 한국어 번역을 수행
2. 해당 문서에 대한 사이드바 변경
Closes: #137
=> Translate 'reviewprocess.md' into ko

eng/README.md
번역 내용
1. 패키지 정보
2. CSV 필드
3. 링크 템플릿
Closes: #160
=> Translate 'eng/README.md' into korean

docs/general/implementation.md, docs/tracing/distributed-tracing-conventions.md, docs/tracing/distributed-tracing-conventions.yml
=> Update the docs: 'Distributed tracing'

docs/general/implementation.md
=> Update the docs: 'Dependencies'

CONTRIBUTING.md
- Add `bundle install` to serve ruby app in codespace.
- Add guideline to access website in codespace. (adding `/azure-sdk-korean/`)
- Update guideline to make vscode codespaces.
close: #167
=> docs: add guide to contributing.md

docs/python/documentation.md
원본 문서와 비교하여 누락된 부분을 추가하였습니다.
https://github.com/Azure/azure-sdk/commit/d531c9a3ea1dc2a92cc81a26a2368e63579159a8
=> Updated the documentation to reflect original

CONTRIBUTING.md
원본 저장소의 변경 사항을 반영하여 번역을 완료하였습니다.
세부사항:
- jekyll 빌드시 --incremental 옵션 추가
- azure-sdk-korean 주소 업데이트
Closes: #187
=> Translate CONTRIBUTING.md reflect most recent doc
